-- Governança de identidade, permissões e solicitações de acesso.

create table if not exists public.usuarios_acesso_eventos (
  id bigint generated by default as identity primary key,
  usuario_id integer,
  solicitacao_id uuid,
  tenant_id uuid,
  evento text not null,
  ator_id integer,
  detalhes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists usuarios_acesso_eventos_usuario_idx on public.usuarios_acesso_eventos(usuario_id,created_at desc);
create index if not exists usuarios_acesso_eventos_solicitacao_idx on public.usuarios_acesso_eventos(solicitacao_id,created_at desc);
alter table public.usuarios_acesso_eventos enable row level security;

drop function if exists app_private.current_user_is_admin();
create or replace function app_private.current_user_is_admin() returns boolean
language sql security definer set search_path=pg_catalog,public,app_private
as $$ select exists(select 1 from public.usuarios where uuid=auth.uid() and ativo=true and perfil='ADMIN'); $$;
revoke all on function app_private.current_user_is_admin() from public;
grant execute on function app_private.current_user_is_admin() to authenticated;

alter table public.usuarios enable row level security;
drop policy if exists usuarios_self_or_admin_select on public.usuarios;
create policy usuarios_self_or_admin_select on public.usuarios for select to authenticated using (uuid=auth.uid() or app_private.current_user_is_admin());
drop policy if exists usuarios_self_or_admin_update on public.usuarios;
create policy usuarios_self_or_admin_update on public.usuarios for update to authenticated using (uuid=auth.uid() or app_private.current_user_is_admin()) with check (uuid=auth.uid() or app_private.current_user_is_admin());

create or replace function public.fn_proteger_usuario_autogerenciado() returns trigger
language plpgsql security definer set search_path=pg_catalog,public,app_private
as $$
begin
  if auth.uid()=old.uuid and not app_private.current_user_is_admin() then
    if new.perfil is distinct from old.perfil or new.ativo is distinct from old.ativo or new.orgao_id is distinct from old.orgao_id then
      raise exception 'Usuário não pode alterar o próprio perfil, status ou órgão' using errcode='42501';
    end if;
  end if;
  new.updated_at:=now();
  return new;
end;
$$;
drop trigger if exists trg_proteger_usuario_autogerenciado on public.usuarios;
create trigger trg_proteger_usuario_autogerenciado before update on public.usuarios for each row execute function public.fn_proteger_usuario_autogerenciado();

alter table public.usuarios_modulos enable row level security;
drop policy if exists usuarios_modulos_self_or_admin_select on public.usuarios_modulos;
create policy usuarios_modulos_self_or_admin_select on public.usuarios_modulos for select to authenticated using (exists(select 1 from public.usuarios u where u.id=usuario_id and (u.uuid=auth.uid() or app_private.current_user_is_admin())));
drop policy if exists usuarios_modulos_admin_write on public.usuarios_modulos;
create policy usuarios_modulos_admin_write on public.usuarios_modulos for all to authenticated using (app_private.current_user_is_admin()) with check (app_private.current_user_is_admin());

drop policy if exists usuarios_acesso_eventos_admin_select on public.usuarios_acesso_eventos;
create policy usuarios_acesso_eventos_admin_select on public.usuarios_acesso_eventos for select to authenticated using (app_private.current_user_is_admin());

grant select,update on public.usuarios to authenticated;
grant select on public.usuarios_modulos,public.usuarios_acesso_eventos to authenticated;

create or replace function public.admin_listar_usuarios(p_busca text default null,p_ativo boolean default null,p_perfil text default null) returns setof jsonb
language plpgsql security definer set search_path=pg_catalog,public,app_private
as $$
begin
  if not app_private.current_user_is_admin() then raise exception 'Apenas administradores podem listar usuários' using errcode='42501'; end if;
  return query select jsonb_build_object('id',u.id,'uuid',u.uuid,'nome',u.nome,'email',u.email,'cargo',u.cargo,'telefone',u.telefone,'orgao_id',u.orgao_id,'perfil',u.perfil,'ativo',u.ativo,'ultimo_acesso',u.ultimo_acesso,'created_at',u.created_at,'desativado_em',u.desativado_em,'reativado_em',u.reativado_em,'modulos',coalesce((select jsonb_agg(jsonb_build_object('modulo',um.modulo,'permitido',um.permitido) order by um.modulo) from public.usuarios_modulos um where um.usuario_id=u.id),'[]'::jsonb)) from public.usuarios u where (p_busca is null or u.nome ilike '%'||p_busca||'%' or u.email ilike '%'||p_busca||'%') and (p_ativo is null or u.ativo=p_ativo) and (p_perfil is null or u.perfil=p_perfil) order by u.nome limit 500;
end;
$$;
grant execute on function public.admin_listar_usuarios(text,boolean,text) to authenticated;

create or replace function public.admin_listar_solicitacoes_acesso(p_status text default 'PENDENTE') returns setof jsonb
language plpgsql security definer set search_path=pg_catalog,public,app_private
as $$
begin
  if not app_private.current_user_is_admin() then raise exception 'Apenas administradores podem listar solicitações' using errcode='42501'; end if;
  return query select to_jsonb(s) || jsonb_build_object('revisado_nome',(select u.nome from public.usuarios u where u.id=s.revisado_por)) from public.solicitacoes_acesso s where (p_status is null or s.status=p_status) order by s.created_at desc limit 500;
end;
$$;
grant execute on function public.admin_listar_solicitacoes_acesso(text) to authenticated;

create or replace function public.admin_atualizar_usuario(p_usuario_id integer,p_patch jsonb,p_modulos jsonb default '[]'::jsonb) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public,app_private
as $$
declare a integer:=app_private.current_user_id(); u public.usuarios%rowtype; old_json jsonb; new_json jsonb; m jsonb;
begin
  if not app_private.current_user_is_admin() then raise exception 'Apenas administradores podem alterar usuários' using errcode='42501'; end if;
  select * into u from public.usuarios where id=p_usuario_id for update;
  if not found then raise exception 'Usuário não encontrado' using errcode='P0002'; end if;
  if u.id=a and coalesce((p_patch->>'ativo')::boolean,u.ativo)=false then raise exception 'Não é permitido desativar a própria conta administrativa' using errcode='42501'; end if;
  old_json:=to_jsonb(u);
  update public.usuarios set nome=coalesce(nullif(p_patch->>'nome',''),nome),cargo=coalesce(p_patch->>'cargo',cargo),telefone=coalesce(p_patch->>'telefone',telefone),orgao_id=case when p_patch ? 'orgao_id' then nullif(p_patch->>'orgao_id','')::integer else orgao_id end,perfil=coalesce(nullif(p_patch->>'perfil',''),perfil),ativo=case when p_patch ? 'ativo' then (p_patch->>'ativo')::boolean else ativo end,desativado_em=case when p_patch ? 'ativo' and (p_patch->>'ativo')::boolean=false then now() else desativado_em end,reativado_em=case when p_patch ? 'ativo' and (p_patch->>'ativo')::boolean=true then now() else reativado_em end,updated_at=now() where id=p_usuario_id returning * into u;
  if jsonb_typeof(p_modulos)='array' then
    for m in select value from jsonb_array_elements(p_modulos) loop
      insert into public.usuarios_modulos(usuario_id,modulo,permitido,concedido_por,updated_at) values(p_usuario_id,m->>'modulo',coalesce((m->>'permitido')::boolean,false),a,now()) on conflict(usuario_id,modulo) do update set permitido=excluded.permitido,concedido_por=excluded.concedido_por,updated_at=now();
    end loop;
  end if;
  new_json:=to_jsonb(u);
  insert into public.usuarios_acesso_eventos(usuario_id,evento,ator_id,detalhes) values(p_usuario_id,'USUARIO_ATUALIZADO',a,jsonb_build_object('antes',old_json,'depois',new_json,'modulos',p_modulos));
  return new_json || jsonb_build_object('modulos',coalesce((select jsonb_agg(jsonb_build_object('modulo',um.modulo,'permitido',um.permitido) order by um.modulo) from public.usuarios_modulos um where um.usuario_id=p_usuario_id),'[]'::jsonb));
end;
$$;
grant execute on function public.admin_atualizar_usuario(integer,jsonb,jsonb) to authenticated;

create or replace function public.admin_revisar_solicitacao_acesso(p_solicitacao_id uuid,p_aprovar boolean,p_perfil text default null,p_modulos text[] default '{}',p_orgao_id integer default null,p_unidade_id uuid default null,p_tenant_id uuid default null,p_observacao text default null) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public,app_private
as $$
declare a integer:=app_private.current_user_id(); r public.solicitacoes_acesso; out_r public.solicitacoes_acesso;
begin
  if not app_private.current_user_is_admin() then raise exception 'Apenas administradores podem revisar solicitações' using errcode='42501'; end if;
  select * into r from public.solicitacoes_acesso where id=p_solicitacao_id for update;
  if not found then raise exception 'Solicitação não encontrada' using errcode='P0002'; end if;
  if r.status<>'PENDENTE' then raise exception 'Solicitação já revisada' using errcode='22023'; end if;
  if p_aprovar then out_r:=public.aprovar_solicitacao_acesso(p_solicitacao_id,coalesce(p_perfil,r.perfil_solicitado,'SOLICITANTE'),coalesce(p_modulos,r.modulos_solicitados),p_orgao_id,p_unidade_id,p_tenant_id,p_observacao); else out_r:=public.rejeitar_solicitacao_acesso(p_solicitacao_id,p_observacao); end if;
  insert into public.usuarios_acesso_eventos(usuario_id,solicitacao_id,tenant_id,evento,ator_id,detalhes) values((select id from public.usuarios where uuid=r.auth_user_id),r.id,r.tenant_id,case when p_aprovar then 'SOLICITACAO_APROVADA' else 'SOLICITACAO_REJEITADA' end,a,jsonb_build_object('perfil',p_perfil,'modulos',p_modulos,'observacao',p_observacao));
  return to_jsonb(out_r);
end;
$$;
grant execute on function public.admin_revisar_solicitacao_acesso(uuid,boolean,text,text[],integer,uuid,uuid,text) to authenticated;

revoke execute on function public.admin_listar_usuarios(text,boolean,text),public.admin_listar_solicitacoes_acesso(text),public.admin_atualizar_usuario(integer,jsonb,jsonb),public.admin_revisar_solicitacao_acesso(uuid,boolean,text,text[],integer,uuid,uuid,text) from anon;
