-- Homologação — paridade mínima do módulo Atas, Saldos e Pedidos.
-- Somente para o projeto de staging xnktywrdoqlacwmdemfp.
-- Não copia dados de produção e não deve ser aplicada no projeto principal.

CREATE TABLE public.itens_ata (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ata_id integer NOT NULL REFERENCES public.atas(id) ON DELETE CASCADE,
  tenant_id uuid NOT NULL REFERENCES public.app_tenants(id) ON DELETE CASCADE,
  unidade_id uuid REFERENCES public.app_tenant_units(id) ON DELETE SET NULL,
  item_numero text NOT NULL,
  descricao text NOT NULL,
  unidade_medida text NOT NULL DEFAULT 'UN',
  quantidade_contratada numeric NOT NULL CHECK (quantidade_contratada >= 0),
  valor_unitario numeric NOT NULL CHECK (valor_unitario >= 0),
  saldo_quantidade numeric NOT NULL CHECK (saldo_quantidade >= 0),
  saldo_valor numeric NOT NULL CHECK (saldo_valor >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, ata_id, item_numero)
);

CREATE TABLE public.pedidos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.app_tenants(id) ON DELETE CASCADE,
  unidade_id uuid REFERENCES public.app_tenant_units(id) ON DELETE SET NULL,
  numero_pedido text NOT NULL,
  usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  ata_id integer NOT NULL REFERENCES public.atas(id) ON DELETE RESTRICT,
  orgao_solicitante_id integer,
  fornecedor_id integer,
  data_solicitacao date NOT NULL DEFAULT current_date,
  status text NOT NULL DEFAULT 'AGUARDANDO_APROVACAO',
  status_aprovacao text NOT NULL DEFAULT 'AGUARDANDO_APROVACAO',
  aprovado_por integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  data_aprovacao date,
  observacoes text,
  valor_total numeric NOT NULL DEFAULT 0 CHECK (valor_total >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, numero_pedido)
);

CREATE TABLE public.itens_pedido (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.app_tenants(id) ON DELETE CASCADE,
  pedido_id integer NOT NULL REFERENCES public.pedidos(id) ON DELETE CASCADE,
  item_ata_id integer NOT NULL REFERENCES public.itens_ata(id) ON DELETE RESTRICT,
  quantidade_solicitada numeric NOT NULL CHECK (quantidade_solicitada > 0),
  valor_unitario numeric NOT NULL CHECK (valor_unitario >= 0),
  valor_total numeric NOT NULL CHECK (valor_total >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, pedido_id, item_ata_id)
);

CREATE TABLE public.consumos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.app_tenants(id) ON DELETE CASCADE,
  unidade_id uuid REFERENCES public.app_tenant_units(id) ON DELETE SET NULL,
  usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  ata_id integer NOT NULL REFERENCES public.atas(id) ON DELETE RESTRICT,
  item_ata_id integer NOT NULL REFERENCES public.itens_ata(id) ON DELETE RESTRICT,
  orgao_solicitante_id integer,
  quantidade numeric NOT NULL CHECK (quantidade > 0),
  valor_unitario numeric NOT NULL CHECK (valor_unitario >= 0),
  valor_total numeric NOT NULL CHECK (valor_total >= 0),
  data_consumo date NOT NULL DEFAULT current_date,
  observacao text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX itens_ata_tenant_item_idx ON public.itens_ata(tenant_id, id);
CREATE INDEX pedidos_tenant_status_idx ON public.pedidos(tenant_id, status_aprovacao, id);
CREATE INDEX itens_pedido_tenant_pedido_idx ON public.itens_pedido(tenant_id, pedido_id);
CREATE INDEX consumos_tenant_item_idx ON public.consumos(tenant_id, item_ata_id, id);

ALTER TABLE public.itens_ata ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.itens_pedido ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consumos ENABLE ROW LEVEL SECURITY;

CREATE POLICY staging_itens_ata_read ON public.itens_ata FOR SELECT TO authenticated
  USING (app_private.has_tenant_access(tenant_id));
CREATE POLICY staging_itens_ata_manage ON public.itens_ata FOR ALL TO authenticated
  USING (app_private.has_tenant_role(tenant_id, ARRAY['tenant_admin','compras_manager']))
  WITH CHECK (app_private.has_tenant_role(tenant_id, ARRAY['tenant_admin','compras_manager']));

CREATE POLICY staging_pedidos_read ON public.pedidos FOR SELECT TO authenticated
  USING (app_private.has_tenant_access(tenant_id));
CREATE POLICY staging_pedidos_manage ON public.pedidos FOR ALL TO authenticated
  USING (app_private.has_tenant_role(tenant_id, ARRAY['tenant_admin','compras_manager']))
  WITH CHECK (app_private.has_tenant_role(tenant_id, ARRAY['tenant_admin','compras_manager']));

CREATE POLICY staging_itens_pedido_read ON public.itens_pedido FOR SELECT TO authenticated
  USING (app_private.has_tenant_access(tenant_id));
CREATE POLICY staging_itens_pedido_manage ON public.itens_pedido FOR ALL TO authenticated
  USING (app_private.has_tenant_role(tenant_id, ARRAY['tenant_admin','compras_manager']))
  WITH CHECK (app_private.has_tenant_role(tenant_id, ARRAY['tenant_admin','compras_manager']));

CREATE POLICY staging_consumos_read ON public.consumos FOR SELECT TO authenticated
  USING (app_private.has_tenant_access(tenant_id));
CREATE POLICY staging_consumos_manage ON public.consumos FOR ALL TO authenticated
  USING (app_private.has_tenant_role(tenant_id, ARRAY['tenant_admin','compras_manager']))
  WITH CHECK (app_private.has_tenant_role(tenant_id, ARRAY['tenant_admin','compras_manager']));

REVOKE ALL ON public.itens_ata, public.pedidos, public.itens_pedido, public.consumos FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.itens_ata, public.pedidos, public.itens_pedido, public.consumos TO authenticated;

CREATE OR REPLACE FUNCTION public.compras_aprovar_pedido(p_pedido_id integer)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public, app_private
AS $$
DECLARE
  v_user_id integer;
  v_tenant_id uuid;
  v_pedido public.pedidos%ROWTYPE;
  v_item record;
  v_item_ata public.itens_ata%ROWTYPE;
  v_count integer := 0;
  v_total numeric := 0;
BEGIN
  v_user_id := app_private.current_user_id();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Usuário autenticado não encontrado' USING ERRCODE = '42501';
  END IF;

  SELECT p.* INTO v_pedido
  FROM public.pedidos AS p
  WHERE p.id = p_pedido_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pedido % não encontrado', p_pedido_id USING ERRCODE = 'P0002';
  END IF;

  v_tenant_id := v_pedido.tenant_id;
  IF NOT app_private.has_tenant_role(v_tenant_id, ARRAY['tenant_admin','compras_manager']) THEN
    RAISE EXCEPTION 'Usuário sem permissão para aprovar pedidos neste tenant' USING ERRCODE = '42501';
  END IF;

  IF v_pedido.status_aprovacao = 'APROVADO' THEN
    RETURN jsonb_build_object('pedido_id', v_pedido.id, 'status', 'APROVADO', 'idempotente', true, 'itens_aprovados', 0, 'valor_total', coalesce(v_pedido.valor_total, 0));
  END IF;

  IF coalesce(v_pedido.status_aprovacao, '') <> 'AGUARDANDO_APROVACAO' THEN
    RAISE EXCEPTION 'Pedido % não está aguardando aprovação', p_pedido_id USING ERRCODE = '22023';
  END IF;

  FOR v_item IN
    SELECT ip.* FROM public.itens_pedido AS ip
    WHERE ip.pedido_id = v_pedido.id AND ip.tenant_id = v_tenant_id
    ORDER BY ip.id
  LOOP
    SELECT ia.* INTO v_item_ata
    FROM public.itens_ata AS ia
    WHERE ia.id = v_item.item_ata_id AND ia.tenant_id = v_tenant_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Item da ata % não encontrado no tenant do pedido', v_item.item_ata_id USING ERRCODE = 'P0002';
    END IF;
    IF v_item.quantidade_solicitada > coalesce(v_item_ata.saldo_quantidade, 0) THEN
      RAISE EXCEPTION 'Saldo insuficiente para o item %: disponível %, solicitado %', v_item_ata.descricao, coalesce(v_item_ata.saldo_quantidade, 0), v_item.quantidade_solicitada USING ERRCODE = '23514';
    END IF;

    INSERT INTO public.consumos (ata_id, item_ata_id, orgao_solicitante_id, usuario_id, quantidade, valor_unitario, valor_total, data_consumo, observacao, created_at, tenant_id, unidade_id)
    VALUES (v_pedido.ata_id, v_item.item_ata_id, v_pedido.orgao_solicitante_id, v_user_id, v_item.quantidade_solicitada, v_item.valor_unitario, v_item.valor_total, current_date, 'Consumo automático via RPC de aprovação do pedido ' || v_pedido.numero_pedido, now(), v_tenant_id, v_pedido.unidade_id);

    UPDATE public.itens_ata
    SET saldo_quantidade = saldo_quantidade - v_item.quantidade_solicitada,
        saldo_valor = greatest(0, saldo_valor - coalesce(v_item.valor_total, 0)),
        updated_at = now()
    WHERE id = v_item.item_ata_id AND tenant_id = v_tenant_id;

    v_count := v_count + 1;
    v_total := v_total + coalesce(v_item.valor_total, 0);
  END LOOP;

  IF v_count = 0 THEN
    RAISE EXCEPTION 'Pedido % não possui itens para aprovação', p_pedido_id USING ERRCODE = '22023';
  END IF;

  UPDATE public.pedidos
  SET status_aprovacao = 'APROVADO', aprovado_por = v_user_id, data_aprovacao = current_date, status = 'APROVADO', updated_at = now()
  WHERE id = v_pedido.id AND tenant_id = v_tenant_id;

  RETURN jsonb_build_object('pedido_id', v_pedido.id, 'status', 'APROVADO', 'idempotente', false, 'itens_aprovados', v_count, 'valor_total', v_total);
END;
$$;

REVOKE ALL ON FUNCTION public.compras_aprovar_pedido(integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.compras_aprovar_pedido(integer) TO authenticated;
