-- Controles operacionais SaaS: estorno segregado, encerramento e relatórios protegidos.
-- Não apaga consumo nem altera histórico; operações reversas são eventos próprios.

create table if not exists public.pedidos_estornos (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  pedido_id integer not null references public.pedidos(id),
  status text not null default 'SOLICITADO' check (status in ('SOLICITADO','APROVADO','REJEITADO','CANCELADO')),
  justificativa text not null check (length(btrim(justificativa)) >= 10),
  solicitado_por integer not null,
  aprovado_por integer,
  solicitado_em timestamptz not null default now(),
  decidido_em timestamptz,
  observacao_decisao text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pedidos_estornos_itens (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  estorno_id bigint not null references public.pedidos_estornos(id) on delete cascade,
  item_pedido_id integer not null references public.itens_pedido(id),
  item_ata_id integer not null references public.itens_ata(id),
  quantidade numeric not null check (quantidade > 0),
  valor_unitario numeric not null default 0,
  valor_total numeric generated always as (quantidade * valor_unitario) stored,
  created_at timestamptz not null default now()
);

create index if not exists pedidos_estornos_tenant_pedido_idx on public.pedidos_estornos(tenant_id,pedido_id,status);
create index if not exists pedidos_estornos_itens_estorno_idx on public.pedidos_estornos_itens(tenant_id,estorno_id);

alter table public.pedidos_estornos enable row level security;
alter table public.pedidos_estornos_itens enable row level security;

drop policy if exists pedidos_estornos_tenant_scope on public.pedidos_estornos;
create policy pedidos_estornos_tenant_scope on public.pedidos_estornos for all to authenticated
using (tenant_id = app_private.current_tenant_id())
with check (tenant_id = app_private.current_tenant_id());

drop policy if exists pedidos_estornos_itens_tenant_scope on public.pedidos_estornos_itens;
create policy pedidos_estornos_itens_tenant_scope on public.pedidos_estornos_itens for all to authenticated
using (tenant_id = app_private.current_tenant_id())
with check (tenant_id = app_private.current_tenant_id());

grant select, insert, update on public.pedidos_estornos to authenticated;
grant select, insert on public.pedidos_estornos_itens to authenticated;

create or replace function public.compras_solicitar_estorno(
  p_pedido_id integer,
  p_itens jsonb,
  p_justificativa text
) returns jsonb
language plpgsql security invoker
set search_path = pg_catalog, public, app_private
as $$
declare
  v_user_id integer := app_private.current_user_id();
  v_tenant_id uuid := app_private.current_tenant_id();
  v_pedido public.pedidos%rowtype;
  v_estorno_id bigint;
  v_item jsonb;
  v_item_pedido public.itens_pedido%rowtype;
  v_prev numeric;
  v_solicitada numeric;
  v_total numeric := 0;
begin
  if v_user_id is null or v_tenant_id is null then raise exception 'Usuário ou tenant não identificado' using errcode='42501'; end if;
  if length(btrim(coalesce(p_justificativa,''))) < 10 then raise exception 'Justificativa do estorno deve possuir ao menos 10 caracteres' using errcode='22023'; end if;
  select * into v_pedido from public.pedidos where id=p_pedido_id and tenant_id=v_tenant_id for update;
  if not found then raise exception 'Pedido não encontrado no tenant corrente' using errcode='P0002'; end if;
  if v_pedido.status_aprovacao <> 'APROVADO' then raise exception 'Somente pedidos aprovados podem ter estorno solicitado' using errcode='22023'; end if;
  if not jsonb_typeof(p_itens) = 'array' or jsonb_array_length(p_itens)=0 then raise exception 'Informe ao menos um item para estorno' using errcode='22023'; end if;

  insert into public.pedidos_estornos(tenant_id,pedido_id,justificativa,solicitado_por)
  values(v_tenant_id,p_pedido_id,btrim(p_justificativa),v_user_id) returning id into v_estorno_id;

  for v_item in select value from jsonb_array_elements(p_itens) loop
    select * into v_item_pedido from public.itens_pedido where id=(v_item->>'item_pedido_id')::integer and pedido_id=p_pedido_id and tenant_id=v_tenant_id for update;
    if not found then raise exception 'Item do pedido não encontrado: %', v_item->>'item_pedido_id' using errcode='P0002'; end if;
    v_solicitada := (v_item->>'quantidade')::numeric;
    if v_solicitada <= 0 then raise exception 'Quantidade de estorno inválida' using errcode='22023'; end if;
    select coalesce(sum(ei.quantidade),0) into v_prev
      from public.pedidos_estornos_itens ei join public.pedidos_estornos e on e.id=ei.estorno_id
     where ei.tenant_id=v_tenant_id and ei.item_pedido_id=v_item_pedido.id and e.status in ('SOLICITADO','APROVADO');
    if v_prev + v_solicitada > v_item_pedido.quantidade_solicitada then raise exception 'Estorno excede a quantidade consumida do item %', v_item_pedido.id using errcode='23514'; end if;
    if exists (select 1 from public.pedidos_entregas_itens dei join public.pedidos_entregas de on de.id=dei.entrega_id where dei.item_pedido_id=v_item_pedido.id and de.tenant_id=v_tenant_id) then
      raise exception 'Item % possui entrega registrada; use o fluxo de devolução correspondente', v_item_pedido.id using errcode='22023';
    end if;
    insert into public.pedidos_estornos_itens(tenant_id,estorno_id,item_pedido_id,item_ata_id,quantidade,valor_unitario)
    values(v_tenant_id,v_estorno_id,v_item_pedido.id,v_item_pedido.item_ata_id,v_solicitada,v_item_pedido.valor_unitario);
    v_total := v_total + v_solicitada * v_item_pedido.valor_unitario;
  end loop;

  insert into public.pedidos_eventos(tenant_id,pedido_id,evento,ator_id,metadados)
  values(v_tenant_id,p_pedido_id,'ESTORNO_SOLICITADO',v_user_id,jsonb_build_object('estorno_id',v_estorno_id,'valor_total',v_total));
  return jsonb_build_object('estorno_id',v_estorno_id,'pedido_id',p_pedido_id,'status','SOLICITADO','valor_total',v_total);
end;
$$;

grant execute on function public.compras_solicitar_estorno(integer,jsonb,text) to authenticated;

create or replace function public.compras_aprovar_estorno(
  p_estorno_id bigint,
  p_aprovar boolean,
  p_observacao text default null
) returns jsonb
language plpgsql security invoker
set search_path = pg_catalog, public, app_private
as $$
declare
  v_user_id integer := app_private.current_user_id();
  v_tenant_id uuid := app_private.current_tenant_id();
  v_estorno public.pedidos_estornos%rowtype;
  v_item record;
  v_total numeric := 0;
  v_status text;
begin
  if v_user_id is null or v_tenant_id is null then raise exception 'Usuário ou tenant não identificado' using errcode='42501'; end if;
  select * into v_estorno from public.pedidos_estornos where id=p_estorno_id and tenant_id=v_tenant_id for update;
  if not found then raise exception 'Solicitação de estorno não encontrada' using errcode='P0002'; end if;
  if v_estorno.status <> 'SOLICITADO' then raise exception 'Solicitação de estorno já decidida' using errcode='22023'; end if;
  if v_estorno.solicitado_por = v_user_id then raise exception 'Segregação de funções: solicitante não pode aprovar o próprio estorno' using errcode='42501'; end if;
  if not app_private.has_tenant_role(v_tenant_id,array['tenant_admin','compras_manager']) then raise exception 'Usuário sem permissão para decidir estornos' using errcode='42501'; end if;
  v_status := case when p_aprovar then 'APROVADO' else 'REJEITADO' end;
  if p_aprovar then
    for v_item in select ei.*, ia.saldo_quantidade from public.pedidos_estornos_itens ei join public.itens_ata ia on ia.id=ei.item_ata_id and ia.tenant_id=ei.tenant_id where ei.estorno_id=v_estorno.id for update of ia loop
      update public.itens_ata set saldo_quantidade=saldo_quantidade+v_item.quantidade, saldo_valor=saldo_valor+(v_item.quantidade*v_item.valor_unitario), updated_at=now() where id=v_item.item_ata_id and tenant_id=v_tenant_id;
      v_total := v_total + v_item.quantidade*v_item.valor_unitario;
    end loop;
  end if;
  update public.pedidos_estornos set status=v_status, aprovado_por=v_user_id, decidido_em=now(), observacao_decisao=nullif(btrim(coalesce(p_observacao,'')),''), updated_at=now() where id=v_estorno.id;
  insert into public.pedidos_eventos(tenant_id,pedido_id,evento,ator_id,metadados)
  values(v_tenant_id,v_estorno.pedido_id,case when p_aprovar then 'ESTORNO_APROVADO' else 'ESTORNO_REJEITADO' end,v_user_id,jsonb_build_object('estorno_id',v_estorno.id,'valor_total',v_total,'observacao',p_observacao));
  return jsonb_build_object('estorno_id',v_estorno.id,'pedido_id',v_estorno.pedido_id,'status',v_status,'valor_total',v_total);
end;
$$;

grant execute on function public.compras_aprovar_estorno(bigint,boolean,text) to authenticated;

create or replace function public.compras_encerrar_pedido(p_pedido_id integer, p_observacao text default null) returns jsonb
language plpgsql security invoker
set search_path = pg_catalog, public, app_private
as $$
declare
  v_user_id integer := app_private.current_user_id();
  v_tenant_id uuid := app_private.current_tenant_id();
  v_pedido public.pedidos%rowtype;
  v_item record;
  v_entregue numeric;
begin
  if v_user_id is null or v_tenant_id is null then raise exception 'Usuário ou tenant não identificado' using errcode='42501'; end if;
  select * into v_pedido from public.pedidos where id=p_pedido_id and tenant_id=v_tenant_id for update;
  if not found then raise exception 'Pedido não encontrado' using errcode='P0002'; end if;
  if not app_private.has_tenant_role(v_tenant_id,array['tenant_admin','compras_manager']) then raise exception 'Usuário sem permissão para encerrar pedidos' using errcode='42501'; end if;
  if v_pedido.status_aprovacao <> 'APROVADO' then raise exception 'Somente pedidos aprovados podem ser encerrados' using errcode='22023'; end if;
  for v_item in select ip.id,ip.quantidade_solicitada from public.itens_pedido ip where ip.pedido_id=p_pedido_id and ip.tenant_id=v_tenant_id loop
    select coalesce(sum(dei.quantidade),0) into v_entregue from public.pedidos_entregas_itens dei join public.pedidos_entregas de on de.id=dei.entrega_id where dei.item_pedido_id=v_item.id and de.pedido_id=p_pedido_id and de.tenant_id=v_tenant_id;
    if v_entregue < v_item.quantidade_solicitada then raise exception 'Item % ainda possui saldo de entrega pendente: solicitado %, entregue %',v_item.id,v_item.quantidade_solicitada,v_entregue using errcode='22023'; end if;
  end loop;
  update public.pedidos set status='ENCERRADO',status_aprovacao='ENCERRADO',updated_at=now() where id=p_pedido_id and tenant_id=v_tenant_id;
  insert into public.pedidos_eventos(tenant_id,pedido_id,evento,ator_id,metadados) values(v_tenant_id,p_pedido_id,'PEDIDO_ENCERRADO',v_user_id,jsonb_build_object('observacao',p_observacao));
  return jsonb_build_object('pedido_id',p_pedido_id,'status','ENCERRADO');
end;
$$;

grant execute on function public.compras_encerrar_pedido(integer,text) to authenticated;

create or replace view public.compras_vw_pedidos_entregas with (security_invoker=true) as
select p.tenant_id,p.id as pedido_id,p.numero_pedido,p.status,p.status_aprovacao,p.data_solicitacao,
       coalesce(sum(ip.quantidade_solicitada),0) as quantidade_solicitada,
       coalesce(sum(dei.quantidade),0) as quantidade_entregue,
       coalesce(sum(ip.quantidade_solicitada),0)-coalesce(sum(dei.quantidade),0) as quantidade_pendente,
       count(distinct de.id) as entregas_registradas
from public.pedidos p join public.itens_pedido ip on ip.pedido_id=p.id and ip.tenant_id=p.tenant_id
left join public.pedidos_entregas_itens dei on dei.item_pedido_id=ip.id and dei.tenant_id=p.tenant_id
left join public.pedidos_entregas de on de.id=dei.entrega_id and de.tenant_id=p.tenant_id
group by p.tenant_id,p.id,p.numero_pedido,p.status,p.status_aprovacao,p.data_solicitacao;

grant select on public.compras_vw_pedidos_entregas to authenticated;

create or replace view public.compras_vw_saldos_operacionais with (security_invoker=true) as
select ia.tenant_id,ia.id as item_ata_id,ia.ata_id,ia.descricao,ia.quantidade,ia.saldo_quantidade,ia.saldo_valor,
       ia.quantidade_contratada,
       coalesce(sum(pr.quantidade) filter (where pr.status='ATIVA'),0) as quantidade_reservada,
       ia.saldo_quantidade-coalesce(sum(pr.quantidade) filter (where pr.status='ATIVA'),0) as quantidade_utilizavel
from public.itens_ata ia left join public.pedidos_reservas pr on pr.item_ata_id=ia.id and pr.tenant_id=ia.tenant_id
group by ia.tenant_id,ia.id,ia.ata_id,ia.descricao,ia.quantidade_contratada,ia.saldo_quantidade,ia.saldo_valor;

grant select on public.compras_vw_saldos_operacionais to authenticated;

comment on view public.compras_vw_pedidos_entregas is 'Relatório tenant-scoped de pedidos, entregas e pendências.';
comment on view public.compras_vw_saldos_operacionais is 'Relatório tenant-scoped de saldo físico, reservado e utilizável.';
