-- Auditoria técnica canônica — staging e produção.
-- Esta migration implementa rastreabilidade técnica; não constitui certificação jurídica.
-- Leitura de registros e relatórios: somente tenant_admin (Admin municipal).
-- Escrita: somente triggers SECURITY DEFINER; sem INSERT/UPDATE/DELETE para authenticated.

CREATE TABLE public.auditoria_eventos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.app_tenants(id) ON DELETE RESTRICT,
  entidade text NOT NULL CHECK (length(trim(entidade)) > 0),
  entidade_id text NOT NULL CHECK (length(trim(entidade_id)) > 0),
  operacao text NOT NULL CHECK (operacao IN ('INSERT','UPDATE','DELETE')),
  ator_id integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  ator_uuid uuid,
  ocorrido_em timestamptz NOT NULL DEFAULT clock_timestamp(),
  origem text NOT NULL DEFAULT 'database',
  request_id text,
  ip_address text,
  user_agent text,
  justificativa text,
  registro_anterior jsonb,
  registro_novo jsonb,
  campos_alterados jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(campos_alterados) = 'array'),
  metadados jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadados) = 'object'),
  hash_anterior text,
  hash_evento text NOT NULL,
  UNIQUE (tenant_id, id)
);

CREATE INDEX auditoria_eventos_tenant_time_idx
  ON public.auditoria_eventos(tenant_id, ocorrido_em DESC, id DESC);
CREATE INDEX auditoria_eventos_tenant_entity_idx
  ON public.auditoria_eventos(tenant_id, entidade, entidade_id, id DESC);
CREATE INDEX auditoria_eventos_actor_idx
  ON public.auditoria_eventos(tenant_id, ator_id, ocorrido_em DESC);

ALTER TABLE public.auditoria_eventos ENABLE ROW LEVEL SECURITY;
CREATE POLICY auditoria_eventos_admin_read ON public.auditoria_eventos
  FOR SELECT TO authenticated
  USING (app_private.has_tenant_role(tenant_id, ARRAY['tenant_admin']));

REVOKE ALL ON public.auditoria_eventos FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.auditoria_eventos TO authenticated;

CREATE OR REPLACE FUNCTION app_private.bloquear_auditoria_mutacao()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, app_private
AS $$
BEGIN
  RAISE EXCEPTION 'Trilha de auditoria é append-only; mutação não permitida' USING ERRCODE = '42501';
END;
$$;

CREATE TRIGGER auditoria_eventos_append_only
  BEFORE UPDATE OR DELETE ON public.auditoria_eventos
  FOR EACH ROW EXECUTE FUNCTION app_private.bloquear_auditoria_mutacao();

CREATE OR REPLACE FUNCTION app_private.registrar_auditoria_canonica()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, app_private, extensions
AS $$
DECLARE
  v_old jsonb;
  v_new jsonb;
  v_row jsonb;
  v_tenant uuid;
  v_entity_id text;
  v_actor_id integer;
  v_actor_uuid uuid;
  v_prev_hash text;
  v_payload jsonb;
  v_hash text;
  v_changed jsonb;
  v_request_id text;
  v_ip text;
  v_user_agent text;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_old := to_jsonb(OLD);
    v_row := v_old;
  ELSIF TG_OP = 'UPDATE' THEN
    v_old := to_jsonb(OLD);
    v_new := to_jsonb(NEW);
    v_row := v_new;
  ELSE
    v_new := to_jsonb(NEW);
    v_row := v_new;
  END IF;

  v_tenant := nullif(v_row->>'tenant_id','')::uuid;
  v_entity_id := coalesce(v_row->>'id', v_row->>'uuid');
  IF v_tenant IS NULL OR v_entity_id IS NULL THEN
    RAISE EXCEPTION 'Auditoria canônica exige tenant_id e id na entidade %', TG_TABLE_NAME USING ERRCODE = '23514';
  END IF;

  v_actor_id := app_private.current_user_id();
  v_actor_uuid := auth.uid();
  v_request_id := nullif(current_setting('request.id', true), '');
  v_ip := coalesce(nullif((nullif(current_setting('request.headers', true), '')::jsonb ->> 'x-forwarded-for'), ''), nullif((nullif(current_setting('request.headers', true), '')::jsonb ->> 'x-real-ip'), ''));
  v_user_agent := nullif((nullif(current_setting('request.headers', true), '')::jsonb ->> 'user-agent'), '');

  SELECT jsonb_agg(key ORDER BY key)
    INTO v_changed
  FROM (
    SELECT key FROM jsonb_each(coalesce(v_old, '{}'::jsonb))
    UNION
    SELECT key FROM jsonb_each(coalesce(v_new, '{}'::jsonb))
  ) AS keys
  WHERE coalesce(v_old -> key, 'null'::jsonb) IS DISTINCT FROM coalesce(v_new -> key, 'null'::jsonb);
  v_changed := coalesce(v_changed, '[]'::jsonb);

  PERFORM pg_advisory_xact_lock(hashtextextended(v_tenant::text, 0));
  SELECT hash_evento INTO v_prev_hash
  FROM public.auditoria_eventos
  WHERE tenant_id = v_tenant
  ORDER BY id DESC
  LIMIT 1
  FOR UPDATE;

  v_payload := jsonb_build_object(
    'tenant_id', v_tenant,
    'entidade', TG_TABLE_NAME,
    'entidade_id', v_entity_id,
    'operacao', TG_OP,
    'ator_id', v_actor_id,
    'ator_uuid', v_actor_uuid,
    'ocorrido_em', clock_timestamp(),
    'request_id', v_request_id,
    'registro_anterior', v_old,
    'registro_novo', v_new,
    'campos_alterados', v_changed,
    'hash_anterior', v_prev_hash
  );
  v_hash := encode(extensions.digest(convert_to(v_payload::text, 'UTF8'), 'sha256'), 'hex');

  INSERT INTO public.auditoria_eventos(
    tenant_id, entidade, entidade_id, operacao, ator_id, ator_uuid,
    ocorrido_em, origem, request_id, ip_address, user_agent,
    registro_anterior, registro_novo, campos_alterados, metadados,
    hash_anterior, hash_evento
  ) VALUES (
    v_tenant, TG_TABLE_NAME, v_entity_id, TG_OP, v_actor_id, v_actor_uuid,
    clock_timestamp(), 'database_trigger', v_request_id, v_ip, v_user_agent,
    v_old, v_new, v_changed,
    jsonb_build_object('trigger', TG_NAME, 'schema', TG_TABLE_SCHEMA),
    v_prev_hash, v_hash
  );

  IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END;
$$;

-- View de relatório. A segurança efetiva vem da RLS da tabela com security_invoker.
CREATE VIEW public.auditoria_eventos_relatorio
WITH (security_invoker = true)
AS
SELECT id, tenant_id, entidade, entidade_id, operacao, ator_id, ator_uuid,
       ocorrido_em, origem, request_id, ip_address, user_agent,
       justificativa, registro_anterior, registro_novo, campos_alterados,
       metadados, hash_anterior, hash_evento
FROM public.auditoria_eventos;

REVOKE ALL ON public.auditoria_eventos_relatorio FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.auditoria_eventos_relatorio TO authenticated;

-- Restringe também os registros legados a Admin, sem apagar seu conteúdo.
DO $$
BEGIN
  IF to_regclass('public.compras_eventos_auditoria') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.compras_eventos_auditoria ENABLE ROW LEVEL SECURITY';
    EXECUTE 'DROP POLICY IF EXISTS compras_auditoria_read ON public.compras_eventos_auditoria';
    EXECUTE 'CREATE POLICY compras_auditoria_admin_read ON public.compras_eventos_auditoria FOR SELECT TO authenticated USING (app_private.has_tenant_role(tenant_id, ARRAY[''tenant_admin'']))';
  END IF;
  IF to_regclass('public.atas_historico') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS atas_historico_tenant_scope ON public.atas_historico';
    EXECUTE 'CREATE POLICY atas_historico_admin_read ON public.atas_historico FOR SELECT TO authenticated USING (app_private.has_tenant_role(tenant_id, ARRAY[''tenant_admin'']))';
  END IF;
  IF to_regclass('public.logs_operacoes') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS logs_operacoes_tenant_scope ON public.logs_operacoes';
    EXECUTE 'CREATE POLICY logs_operacoes_admin_read ON public.logs_operacoes FOR SELECT TO authenticated USING (app_private.has_tenant_role(tenant_id, ARRAY[''tenant_admin'']))';
  END IF;
END;
$$;

-- Audita entidades críticas que possuem tenant_id. O bloco é condicional para
-- permitir a mesma migration em staging e produção com paridade diferente.
DO $$
DECLARE
  v_table text;
  v_trigger text := 'auditoria_canonica_trigger';
BEGIN
  FOREACH v_table IN ARRAY ARRAY[
    'app_tenant_memberships',
    'compras_fluxos', 'compras_fluxo_versoes', 'compras_fluxo_etapas', 'compras_fluxo_subetapas',
    'compras_processos', 'compras_processos_etapas', 'compras_processos_subetapas',
    'compras_documentos', 'compras_artefatos', 'compras_artefato_versoes',
    'compras_regras_versoes', 'compras_decisoes',
    'itens_ata', 'pedidos', 'itens_pedido', 'consumos'
  ] LOOP
    IF to_regclass('public.' || v_table) IS NOT NULL
       AND EXISTS (
         SELECT 1 FROM information_schema.columns
         WHERE table_schema='public' AND table_name=v_table AND column_name='tenant_id'
       )
       AND NOT EXISTS (
         SELECT 1 FROM pg_trigger t
         JOIN pg_class c ON c.oid=t.tgrelid
         JOIN pg_namespace n ON n.oid=c.relnamespace
         WHERE t.tgname=v_trigger AND n.nspname='public' AND c.relname=v_table AND NOT t.tgisinternal
       ) THEN
      EXECUTE format('CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION app_private.registrar_auditoria_canonica()', v_trigger, v_table);
    END IF;
  END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION app_private.registrar_auditoria_canonica() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION app_private.bloquear_auditoria_mutacao() FROM PUBLIC, anon, authenticated;
