-- Fechamento operacional: validação server-side de entrega final e ocorrências.

create table if not exists public.pedidos_ocorrencias (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  pedido_id integer not null references public.pedidos(id),
  entrega_id uuid references public.pedidos_entregas(id),
  tipo text not null check (tipo in ('DIVERGENCIA','AVARIA','ATRASO','RECUSA','DEVOLUCAO','OUTRA')),
  severidade text not null default 'NORMAL' check (severidade in ('NORMAL','ALTA','CRITICA')),
  descricao text not null check (length(btrim(descricao)) >= 5),
  resolvida boolean not null default false,
  registrada_por integer not null,
  resolvida_por integer,
  resolvida_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists pedidos_ocorrencias_tenant_pedido_idx on public.pedidos_ocorrencias(tenant_id,pedido_id,created_at desc);
alter table public.pedidos_ocorrencias enable row level security;
drop policy if exists pedidos_ocorrencias_tenant_scope on public.pedidos_ocorrencias;
create policy pedidos_ocorrencias_tenant_scope on public.pedidos_ocorrencias for select to authenticated using(tenant_id=app_private.current_tenant_id());
grant select on public.pedidos_ocorrencias to authenticated;

create or replace function public.compras_registrar_ocorrencia(p_pedido_id integer,p_tipo text,p_descricao text,p_severidade text default 'NORMAL',p_entrega_id uuid default null) returns jsonb
language plpgsql security invoker set search_path=pg_catalog,public,app_private
as $$
declare uid integer:=app_private.current_user_id(); tid uuid:=app_private.current_tenant_id(); p public.pedidos; o public.pedidos_ocorrencias;
begin
  if uid is null or tid is null then raise exception 'Usuário ou tenant não identificado' using errcode='42501'; end if;
  if p_tipo not in ('DIVERGENCIA','AVARIA','ATRASO','RECUSA','DEVOLUCAO','OUTRA') then raise exception 'Tipo de ocorrência inválido' using errcode='22023'; end if;
  if p_severidade not in ('NORMAL','ALTA','CRITICA') then raise exception 'Severidade inválida' using errcode='22023'; end if;
  if length(btrim(coalesce(p_descricao,'')))<5 then raise exception 'Descrição da ocorrência deve possuir ao menos 5 caracteres' using errcode='22023'; end if;
  select * into p from public.pedidos where id=p_pedido_id and tenant_id=tid for update;
  if not found then raise exception 'Pedido não encontrado no tenant corrente' using errcode='P0002'; end if;
  if not app_private.has_tenant_role(tid,array['tenant_admin','compras_manager']) then raise exception 'Sem permissão para registrar ocorrência' using errcode='42501'; end if;
  insert into public.pedidos_ocorrencias(tenant_id,pedido_id,entrega_id,tipo,severidade,descricao,registrada_por) values(tid,p_pedido_id,p_entrega_id,p_tipo,p_severidade,btrim(p_descricao),uid) returning * into o;
  perform app_private.registrar_evento_pedido(p_pedido_id,'OCORRENCIA_REGISTRADA',p.status_aprovacao,p.status_aprovacao,btrim(p_descricao),jsonb_build_object('ocorrencia_id',o.id,'tipo',p_tipo,'severidade',p_severidade));
  return jsonb_build_object('ocorrencia_id',o.id,'pedido_id',p_pedido_id,'tipo',p_tipo,'severidade',p_severidade);
end;
$$;
grant execute on function public.compras_registrar_ocorrencia(integer,text,text,text,uuid) to authenticated;

create or replace function public.compras_registrar_entrega(p_pedido_id integer,p_itens jsonb,p_tipo text default 'PARCIAL',p_data_entrega date default current_date,p_documento text default null,p_observacao text default null) returns jsonb
language plpgsql security invoker set search_path=pg_catalog,public,app_private
as $$
declare p public.pedidos; e public.pedidos_entregas; x jsonb; ip public.itens_pedido%rowtype; entregue numeric; nova numeric; n integer; uid integer; tid uuid; faltantes integer;
begin
  uid:=app_private.current_user_id(); tid:=app_private.current_tenant_id();
  if uid is null or tid is null then raise exception 'Usuário ou tenant não identificado' using errcode='42501'; end if;
  if p_tipo not in ('PARCIAL','FINAL') then raise exception 'Tipo de entrega inválido' using errcode='22023'; end if;
  if p_data_entrega is null or p_data_entrega>current_date then raise exception 'Data de entrega inválida' using errcode='22023'; end if;
  select * into p from public.pedidos where id=p_pedido_id and tenant_id=tid for update;
  if not found then raise exception 'Pedido não encontrado' using errcode='P0002'; end if;
  if p.status_aprovacao<>'APROVADO' then raise exception 'Somente pedidos aprovados podem receber entrega' using errcode='22023'; end if;
  if not app_private.has_tenant_role(tid,array['tenant_admin','compras_manager']) then raise exception 'Sem permissão para registrar entrega' using errcode='42501'; end if;
  if jsonb_typeof(coalesce(p_itens,'[]'::jsonb))<>'array' or jsonb_array_length(p_itens)=0 then raise exception 'Entrega sem itens' using errcode='22023'; end if;
  select coalesce(max(numero),0)+1 into n from public.pedidos_entregas where pedido_id=p_pedido_id and tenant_id=tid;
  insert into public.pedidos_entregas(pedido_id,tenant_id,numero,data_entrega,tipo,documento_referencia,observacao,recebido_por) values(p_pedido_id,tid,n,p_data_entrega,nullif(btrim(p_tipo),''),nullif(btrim(p_documento),''),nullif(btrim(p_observacao),''),uid) returning * into e;
  for x in select value from jsonb_array_elements(p_itens) loop
    select * into ip from public.itens_pedido where id=(x->>'item_pedido_id')::integer and pedido_id=p_pedido_id and tenant_id=tid for update;
    if not found then raise exception 'Item de pedido inválido' using errcode='P0002'; end if;
    nova:=(x->>'quantidade')::numeric;
    if nova is null or nova<=0 then raise exception 'Quantidade de entrega inválida' using errcode='22023'; end if;
    select coalesce(sum(quantidade),0) into entregue from public.pedidos_entregas_itens where item_pedido_id=ip.id and tenant_id=tid;
    if entregue+nova>ip.quantidade_solicitada then raise exception 'Entrega excede quantidade do item %',ip.id using errcode='22023'; end if;
    insert into public.pedidos_entregas_itens(entrega_id,pedido_id,item_pedido_id,tenant_id,quantidade,observacao) values(e.id,p_pedido_id,ip.id,tid,nova,nullif(btrim(x->>'observacao'),''));
  end loop;
  if p_tipo='FINAL' then
    select count(*) into faltantes from public.itens_pedido ip where ip.pedido_id=p_pedido_id and ip.tenant_id=tid and (select coalesce(sum(dei.quantidade),0) from public.pedidos_entregas_itens dei where dei.item_pedido_id=ip.id and dei.tenant_id=tid)<ip.quantidade_solicitada;
    if faltantes>0 then raise exception 'Recebimento final incompleto: % item(ns) pendente(s)',faltantes using errcode='22023'; end if;
  end if;
  perform app_private.registrar_evento_pedido(p_pedido_id,'ENTREGA_REGISTRADA',p.status_aprovacao,p.status_aprovacao,p_observacao,jsonb_build_object('entrega_id',e.id,'numero',e.numero,'tipo',p_tipo));
  return jsonb_build_object('entrega_id',e.id,'numero',e.numero,'pedido_id',p_pedido_id,'tipo',p_tipo);
end;
$$;
grant execute on function public.compras_registrar_entrega(integer,jsonb,text,date,text,text) to authenticated;
